
CREATE TABLE TEST_SCHEMA.RENTING_CARS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  brand VARCHAR(250) NOT NULL,
  model VARCHAR(250) NOT NULL,
  modelYear NUMBER DEFAULT NULL,
  dailyRentPrice NUMBER DEFAULT NULL
);

create sequence RENTALS_SEQ
START WITH 1
INCREMENT BY 1
  MINVALUE 1
;

CREATE TABLE TEST_SCHEMA.RENTALS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  customername VARCHAR(250) NOT NULL,
  brand VARCHAR(250) NOT NULL,
  model VARCHAR(250) NOT NULL,
  modelYear NUMBER DEFAULT NULL,
  dailyRentPrice NUMBER DEFAULT NULL
);
